name: data_client
description: generic, abstract interface (DataClient<T>) for interacting with data resources of type T.
repository: https://github.com/flutter-news-app-full-source-code/data-client
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: d7d9afa3e0cf8fb211fdea3342db8831813abf7d

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
